### PR TITLE
Geordies styling changes

### PR DESCRIPTION
**Pull request by bradystroud**
Changes from #394

### CODE REVIEW

**Comment by bradystroud** [comment]
Hey @Geordie88 @tiagov8,

I am not sure why #394 is failing, but I have moved the changes to this PR which is succeeding 🎉.
1. Please approve so I can merge in these changes

Thanks

**Review by Geordie88 — APPROVED** [review]

**Review by JackDevAU — APPROVED** [review]

**Comment by tiagov8** [comment]
Hey @bradystroud 

I assume this has all been solved... When do we expect the changes to be live?

Thanks,

**Comment by bradystroud** [comment]
Hey @tiagov8

@JackDevAU has triggered a release, the changes should be live later today

Thanks,

**Comment by JackDevAU** [comment]
Hey @tiagov8 & @Geordie88,

As Brady mentioned I just created a new release. On build I noticed that there were some issues, so I have reverted back to an earlier version [Commit: 1a6b47f7bddd14614a4c2b4922d28ae0ecf8b35e](https://github.com/SSWConsulting/SSW.People/commit/1a6b47f7bddd14614a4c2b4922d28ae0ecf8b35e)

The major issue was to do with some CSS changes introduced in this PR. Please see the below screenshot and fix according. Cheers :) 

### Screenshots 
image
**Figure: red square appearing before ul and li elements**
 
image
**Figure: red square appearing before ul and li elements**

**Pull request merged**
